name: Go CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.3'

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run linters
        run: |
          go run golang.org/x/tools/cmd/staticcheck

      - name: Run tests
        run: |
          go test -v ./...

  build-docker-image:
    needs: lint-and-test
    uses: ./.github/workflows/docker-ci.yml  
